version: '3.7'

services:
  # Backend API
  authy-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/authy/server
    environment:
      POSTGRES_URI: postgres://johnny:secret@postgres:5432/authy-db
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/authy/server
      - /usr/src/authy/server/node_modules/

  # Postgres DB
  postgres:
    environment:
      POSTGRES_USER: johnny
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authy-db
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"


